services:
  app_proxy:
    environment:
      APP_HOST: lilli-redirect
      APP_PORT: 80

  immich-redirect:
    image: nginx:alpine
    volumes:
      - /Volumes/umbrel-data/app-data/lilli-redirect/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
