services:
  app_proxy:
    environment:
      APP_HOST: lilli-redirect
      APP_PORT: 8002

  immich-redirect:
    image: nginx:alpine
    volumes:
      - /nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
