version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: lilli-redirect
      APP_PORT: 80
    container_name: lilli-redirect_app_proxy_1
  web:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '8001:80'
    volumes:
      - /Volumes/umbrel-data/app-data/lilli-redirect/proxy-html:/usr/share/nginx/html:ro
    container_name: lilli-redirect_web_1
