version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lilli-redirect
      APP_PORT: 8001

  web:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8001:80"
    volumes:
      - ./proxy-html:/usr/share/nginx/html:ro
